# Main Menu
SYNC = "1"
AUTOMATION = "2"
MANUAL_SEARCH = "3"
LIBRARY_SEARCH = "4"
COLLECTIONS = "5"
STATISTICS = "6"
COMPARE = "7"
REPAIR = "8"
BULK_OPS = "9"
PLUGINS = "10"
ABOUT = "11"
TOOLS = "12"
EXIT = "13"

# Generic Back
BACK = "10"
BACK_8 = "8"
BACK_7 = "7"
BACK_4 = "4"
BACK_3 = "3"

# Tools sub-menus
TOOLS_EXPORT = "1"
TOOLS_IMPORT = "2"
TOOLS_BACKUP = "3"
TOOLS_RESTORE = "4"
TOOLS_ALIAS = "5"
TOOLS_CACHE = "6"
TOOLS_RETRY = "7"
TOOLS_SETTINGS = "8"
TOOLS_HEALTH = "9"

# Export Center
EXPORT_ANILIST = "1"
EXPORT_MAL = "2"
EXPORT_TELEGRAM = "3"
EXPORT_MISSING = "4"
EXPORT_RETRY = "5"
EXPORT_ALIASES = "6"
EXPORT_CACHE = "7"
EXPORT_BACK = "8"

# Import Center
IMPORT_ALIASES = "1"
IMPORT_RETRY = "2"
IMPORT_CACHE = "3"
IMPORT_SETTINGS = "4"
IMPORT_TELEGRAM = "5"
IMPORT_CUSTOM = "6"
IMPORT_BACK = "7"

# Settings
SETTINGS_BASIC = "1"
SETTINGS_ADVANCED = "2"
SETTINGS_BACK = "3"

# Export Format
FMT_JSON = "1"
FMT_CSV = "2"
FMT_TXT = "3"
FMT_MD = "4"
FMT_HTML = "5"
FMT_XLSX = "6"
FMT_CANCEL = "7"

# Bulk Operations
BULK_REFRESH_AL = "1"
BULK_REFRESH_MAL = "2"
BULK_REFRESH_ALL = "3"
BULK_HEALTH = "4"
BULK_REPAIR_MAL = "5"
BULK_DEDUP = "6"
BULK_CLEAN = "7"
BULK_REBUILD = "8"
BULK_OPTIMIZE = "9"

# Bulk Tools (router)
BULK_TOOL_MAL = "1"
BULK_TOOL_AL = "2"
BULK_TOOL_BOTH = "3"
BULK_TOOL_CACHE = "4"
BULK_TOOL_RETRY = "5"
BULK_TOOL_DEDUP = "6"
BULK_TOOL_CLEAN = "7"
BULK_TOOL_STATS = "8"
BULK_TOOL_VERIFY = "9"

# Alias Manager
ALIAS_VIEW = "1"
ALIAS_SEARCH = "2"
ALIAS_EDIT = "3"
ALIAS_MERGE = "4"
ALIAS_DELETE = "5"
ALIAS_DEDUP = "6"
ALIAS_STATS = "7"
ALIAS_BACK = "8"

# Retry Queue
RETRY_VIEW = "1"
RETRY_REMOVE = "2"
RETRY_CLEAR = "3"
RETRY_BACK = "4"

# Search Cache
CACHE_VIEW = "1"
CACHE_SEARCH = "2"
CACHE_DELETE = "3"
CACHE_CLEAR = "4"
CACHE_EXPORT = "5"
CACHE_STATS = "6"
CACHE_BACK = "7"

# Automation
AUTO_TOGGLE = "1"
AUTO_INTERVAL = "2"
AUTO_STARTUP = "3"
AUTO_LIVE = "4"
AUTO_BACKUP = "5"
AUTO_HEALTH = "6"
AUTO_BACK = "7"

# Repair
REPAIR_ANILIST = "1"
REPAIR_NOT_FOUND = "2"
REPAIR_AUTO = "3"
REPAIR_BACK = "4"

# Collection Manager
COL_CREATE = "+"
COL_EDIT = "e"
COL_STATS = "s"
COL_EXPORT = "x"
COL_ICON = "i"
COL_RENAME = "r"
COL_DELETE = "d"

# Collection Edit sub-menu
COL_VIEW = "1"
COL_ADD = "2"
COL_REMOVE = "3"

# Pagination
PAGE_NEXT = "n"
PAGE_PREV = "p"
PAGE_BACK = "q"

# Item actions
ACTION_YES = "y"
ACTION_NO = "n"
ACTION_QUIT = "q"

# Related Anime (sync)
RELATED_ADD_ALL = "2"
RELATED_SEARCH = "3"
RELATED_ORDER = "4"
RELATED_CHOOSE = "5"
RELATED_CANCEL = "6"
